"""The sequence of triangle numbers is generated by adding the natural numbers. So the the 7th triangle number would be 1+2+3+4+5+6+7 = 28. The first ten terms would be:

Let us list the factors of the first seven triangle numbers:

 
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from tqdm import tqdm
import math

num = 2034567890987654


def generateTriangles(max):
    previousTriangle = 1
    Triangles = [1]
    for i in range(2,max):
        num = i + previousTriangle
        Triangles.append(num)
        previousTriangle = num
    return Triangles

def fullyfactorise(num):

    primeFactors = []

    factor = 2
    while True:
        if num % factor == 0:
            num /= factor
            primeFactors.append(factor)
            print(num)
        else:
            break

    factor = 3
    while factor <= num:
        if num % factor == 0:
            num /= factor           
            primeFactors.append(factor)
        factor += 2


        


    
    return primeFactors


 

print(fullyfactorise(num))


#print(generateTriangles(10000))

        