"""The sequence of triangle numbers is generated by adding the natural numbers. So the the 7th triangle number would be 1+2+3+4+5+6+7 = 28. The first ten terms would be:

Let us list the factors of the first seven triangle numbers:

 
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from tqdm import tqdm
import math

num = 20


def generateTriangles(max):
    previousTriangle = 1
    Triangles = [1]
    for i in range(2,max):
        num = i + previousTriangle
        Triangles.append(num)
        previousTriangle = num
    return Triangles

def fullyfactorise(num):

    primeFactors = []

    factor = 2
    while True:
        if num % factor == 0:
            num /= factor
            primeFactors.append(factor)
            print(num)
        else:
            break
    for factor in range(3, int(math.sqrt(num)+2), 2):
        while True:
            if num % factor == 0:
                num /= factor
                
                primeFactors.append(factor)
            else:
                break
        if num == 1: #fix this part 
            break

        


    
    return primeFactors


 

print(fullyfactorise(num))


#print(generateTriangles(10000))

        