"""The sequence of triangle numbers is generated by adding the natural numbers. So the the 7th triangle number would be 1+2+3+4+5+6+7 = 28. The first ten terms would be:

Let us list the factors of the first seven triangle numbers:

* * * * * * * 
 
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from tqdm import tqdm 
import math



def generateTriangles(max):
    previousTriangle = 1
    Triangles = [1]
    for i in range(2,max):
        num = i + previousTriangle
        Triangles.append(num)
        previousTriangle = num
    return Triangles

def fullyfactorise(num):

    primeFactors = []
    sqrt = num**0.5
    factor = 2
    while True:
        if num % factor == 0:
            num /= factor
            primeFactors.append(factor)
        else:
            break

    factor = 3
    while factor < sqrt+1:
        if num % factor == 0:
            num /= factor           
            primeFactors.append(factor)
        else:
            factor += 2
    
    if num > 1:
        primeFactors.append(int(num))

    return primeFactors

def formatNum(primeFactors):
    """
    Formats a list of prime factors into one with the base to the power of an exponent

    Args:
        primeFactors (array): list of prime factors of num

    Returns:
        2D array: Base**exponent
    """
    formattedNum = [[]]
    for i, prime in enumerate(primeFactors):
        if primeFactors[i-1] == prime:
            continue
        else:
            formattedNum.append([prime, primeFactors.count(prime)])
    formattedNum.remove([])
    return formattedNum


def calculateNumFactors(formattedArray):
    numFactors = 1
    for baseXexponent in formattedArray:
        numFactors *= (baseXexponent[1]+1)
    return numFactors
 

triangles = generateTriangles(1_000_000)

for triangle in triangles:
    numFactors = calculateNumFactors(formatNum(fullyfactorise(triangle)))
    if numFactors > 500:
        print(triangle, "has over 500 factors.", (numFactors))
        break
